on makeDate(dayValue, hourValue, minuteValue)
	set d to current date
	set year of d to 2026
	set month of d to June
	set day of d to dayValue
	set time of d to (hourValue * hours + minuteValue * minutes)
	return d
end makeDate

with timeout of 900 seconds
tell application "Calendar"
	set scheduleName to "NY Tech Week 2026 - Schedule"
	set referenceName to "NY Tech Week 2026 - All RSVPs"
	if not (exists calendar scheduleName) then make new calendar with properties {name:scheduleName}
	if not (exists calendar referenceName) then make new calendar with properties {name:referenceName}
	set scheduleCal to calendar scheduleName
	set referenceCal to calendar referenceName
	set windowStart to my makeDate(1, 0, 0)
	set windowEnd to my makeDate(8, 0, 0)
	delete (every event of scheduleCal whose start date is greater than or equal to windowStart and start date is less than windowEnd)
	delete (every event of referenceCal whose start date is greater than or equal to windowStart and start date is less than windowEnd)

	-- Operational route with transit blocks.
	make new event at end of events of scheduleCal with properties {summary:"[TW-6408-TRAVEL-IN] FiDi home base -> Beyond the Spec Masterclass: Engineering in the Age of Agents", start date:my makeDate(1, 13, 22), end date:my makeDate(1, 14, 0), location:"FiDi home base -> Flatiron", description:"TechWeekID: TW-6408\nCalendarBlockID: TW-6408-TRAVEL-IN\nRerankID: \nPartifulID: FHiuNwzr13e3YBI4ssUX\nWalk 0 min to Wall St (2/3); subway 31 min; walk 2 min from 23 St-Baruch College (4/6); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: FiDi home base -> Flatiron ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/FHiuNwzr13e3YBI4ssUX"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-6408] [PENDING] Beyond the Spec Masterclass: Engineering in the Age of Agents", start date:my makeDate(1, 14, 0), end date:my makeDate(1, 15, 0), location:"Flatiron", description:"TechWeekID: TW-6408\nCalendarBlockID: TW-6408-SCHEDULE\nRerankID: 6408\nPartifulID: FHiuNwzr13e3YBI4ssUX\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: primary\nVenue basis: IBM One Madison Avenue, 1 Madison Ave,, New York, NY 10010 (exact_from_partiful_maps)\nRank/tier/score: 24 / S / 74\nURL: https://partiful.com/e/FHiuNwzr13e3YBI4ssUX"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-44-TRAVEL-IN] Beyond the Spec Masterclass: Engineering in the Age of Agents -> From Vibe Coding to AI-Driven Development", start date:my makeDate(1, 15, 50), end date:my makeDate(1, 16, 0), location:"Beyond the Spec Masterclass: Engineering in the Age of Agents -> WeWork, 135 Madison Ave, New York, NY", description:"TechWeekID: TW-44\nCalendarBlockID: TW-44-TRAVEL-IN\nRerankID: \nPartifulID: xowd9F3kB7mPFN1luUwY\nWalk approx 10 min / 767 m using OSM-geocoded points.\nRSVP status: registered\nCategory: travel\nVenue basis: Beyond the Spec Masterclass: Engineering in the Age of Agents -> WeWork, 135 Madison Ave, New York, NY ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/xowd9F3kB7mPFN1luUwY"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-44] [PENDING] From Vibe Coding to AI-Driven Development", start date:my makeDate(1, 16, 0), end date:my makeDate(1, 17, 0), location:"WeWork, 135 Madison Ave, New York, NY", description:"TechWeekID: TW-44\nCalendarBlockID: TW-44-SCHEDULE\nRerankID: 44\nPartifulID: xowd9F3kB7mPFN1luUwY\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=2; plusOne=TBD.\nRSVP status: applied\nCategory: primary\nVenue basis: WeWork, 135 Madison Ave, New York, NY (exact_from_signup_status)\nRank/tier/score: 29 / A / 71\nURL: https://partiful.com/e/xowd9F3kB7mPFN1luUwY"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5978-TRAVEL-IN] From Vibe Coding to AI-Driven Development -> Open Source Must Win", start date:my makeDate(1, 17, 28), end date:my makeDate(1, 18, 0), location:"From Vibe Coding to AI-Driven Development -> Lower East Side", description:"TechWeekID: TW-5978\nCalendarBlockID: TW-5978-TRAVEL-IN\nRerankID: \nPartifulID: OF1vP5L8dtXKRtInyWKs\nWalk 3 min to 33 St (4/6); subway 23 min; walk 1 min from Delancey St-Essex St (F); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: From Vibe Coding to AI-Driven Development -> Lower East Side ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/OF1vP5L8dtXKRtInyWKs?c=s6u4EYds"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5978] [PENDING] Open Source Must Win", start date:my makeDate(1, 18, 0), end date:my makeDate(1, 21, 0), location:"Lower East Side", description:"TechWeekID: TW-5978\nCalendarBlockID: TW-5978-SCHEDULE\nRerankID: 5978\nPartifulID: OF1vP5L8dtXKRtInyWKs\nIf this is not approved, use registered backup NYC B2B at Skinos instead. Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=2; plusOne=TBD.\nRSVP status: applied\nCategory: primary\nVenue basis: Delancey St Essex St, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 37 / A / 64\nURL: https://partiful.com/e/OF1vP5L8dtXKRtInyWKs?c=s6u4EYds"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-20260601-TRAVEL-HOME] Open Source Must Win -> FiDi home base", start date:my makeDate(1, 21, 0), end date:my makeDate(1, 21, 35), location:"Open Source Must Win -> FiDi home base", description:"TechWeekID: TW-5978\nCalendarBlockID: TW-20260601-TRAVEL-HOME\nRerankID: \nPartifulID: OF1vP5L8dtXKRtInyWKs\nWalk approx 35 min / 2751 m using OSM-geocoded points.\nRSVP status: registered\nCategory: travel\nVenue basis: Open Source Must Win -> FiDi home base ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/OF1vP5L8dtXKRtInyWKs?c=s6u4EYds"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4551-TRAVEL-IN] FiDi home base -> How to Write a Book on AI in Enterprise SDLC While Patterns Keep Changing", start date:my makeDate(2, 11, 13), end date:my makeDate(2, 12, 0), location:"FiDi home base -> Midtown", description:"TechWeekID: TW-4551\nCalendarBlockID: TW-4551-TRAVEL-IN\nRerankID: \nPartifulID: M7pXmV8sOXT11yHb9pKw\nWalk 0 min to Wall St (2/3); subway 40 min; walk 2 min from 42 St-Bryant Pk (B/D/F/M); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: FiDi home base -> Midtown ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/M7pXmV8sOXT11yHb9pKw"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4551] [PENDING] How to Write a Book on AI in Enterprise SDLC While Patterns Keep Changing", start date:my makeDate(2, 12, 0), end date:my makeDate(2, 13, 45), location:"Midtown", description:"TechWeekID: TW-4551\nCalendarBlockID: TW-4551-SCHEDULE\nRerankID: 4551\nPartifulID: M7pXmV8sOXT11yHb9pKw\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: primary\nVenue basis: Bryant Park, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 33 / A / 68\nURL: https://partiful.com/e/M7pXmV8sOXT11yHb9pKw"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4341] [PENDING] From Copilot to Control Plane - Visdom", start date:my makeDate(2, 16, 0), end date:my makeDate(2, 17, 30), location:"Midtown", description:"TechWeekID: TW-4341\nCalendarBlockID: TW-4341-SCHEDULE\nRerankID: 4341\nPartifulID: bn5h1g13xzOV6R5XkLaE\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: primary\nVenue basis: Bryant Park, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 1 / S / 100\nURL: https://partiful.com/e/bn5h1g13xzOV6R5XkLaE"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4161-TRAVEL-IN] From Copilot to Control Plane - Visdom -> Future of DevEx", start date:my makeDate(2, 17, 36), end date:my makeDate(2, 18, 0), location:"From Copilot to Control Plane - Visdom -> SoHo", description:"TechWeekID: TW-4161\nCalendarBlockID: TW-4161-TRAVEL-IN\nRerankID: \nPartifulID: 7DYGSiY1WUuRSvEnD5gp\nWalk 2 min to 42 St-Bryant Pk (B/D/F/M); subway 17 min; walk 0 min from Prince St (N/Q/R/W); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: From Copilot to Control Plane - Visdom -> SoHo ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/7DYGSiY1WUuRSvEnD5gp?c=aQ_TnSt9"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4161] [PENDING] Future of DevEx", start date:my makeDate(2, 18, 0), end date:my makeDate(2, 21, 0), location:"SoHo", description:"TechWeekID: TW-4161\nCalendarBlockID: TW-4161-SCHEDULE\nRerankID: 4161\nPartifulID: 7DYGSiY1WUuRSvEnD5gp\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: primary\nVenue basis: Spring St and Broadway, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 3 / S / 100\nURL: https://partiful.com/e/7DYGSiY1WUuRSvEnD5gp?c=aQ_TnSt9"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-20260602-TRAVEL-HOME] Future of DevEx -> FiDi home base", start date:my makeDate(2, 21, 0), end date:my makeDate(2, 21, 20), location:"Future of DevEx -> FiDi home base", description:"TechWeekID: TW-4161\nCalendarBlockID: TW-20260602-TRAVEL-HOME\nRerankID: \nPartifulID: 7DYGSiY1WUuRSvEnD5gp\nWalk 0 min to Prince St (N/Q/R/W); subway 15 min; walk 0 min from Wall St (2/3); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: Future of DevEx -> FiDi home base ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/7DYGSiY1WUuRSvEnD5gp?c=aQ_TnSt9"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5889-TRAVEL-IN] FiDi home base -> Building secure AI for your data: DeepFellow Demo + Q&A", start date:my makeDate(3, 11, 29), end date:my makeDate(3, 12, 0), location:"FiDi home base -> Chelsea", description:"TechWeekID: TW-5889\nCalendarBlockID: TW-5889-TRAVEL-IN\nRerankID: \nPartifulID: 4HvzWY1VZlHgK21fMBUz\nWalk 0 min to Wall St (2/3); subway 22 min; walk 4 min from 23 St (A/C/E); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: FiDi home base -> Chelsea ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/4HvzWY1VZlHgK21fMBUz?c=g5NbnbjN"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5889] [PENDING] Building secure AI for your data: DeepFellow Demo + Q&A", start date:my makeDate(3, 12, 0), end date:my makeDate(3, 13, 15), location:"Chelsea", description:"TechWeekID: TW-5889\nCalendarBlockID: TW-5889-SCHEDULE\nRerankID: 5889\nPartifulID: 4HvzWY1VZlHgK21fMBUz\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: primary\nVenue basis: 23rd Street and 8th Avenue, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 16 / S / 80\nURL: https://partiful.com/e/4HvzWY1VZlHgK21fMBUz?c=g5NbnbjN"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4444-TRAVEL-IN] Building secure AI for your data: DeepFellow Demo + Q&A -> The Future of Coding Agents and IDE", start date:my makeDate(3, 13, 35), end date:my makeDate(3, 14, 0), location:"Building secure AI for your data: DeepFellow Demo + Q&A -> 1155 6th Ave, New York, NY 10036", description:"TechWeekID: TW-4444\nCalendarBlockID: TW-4444-TRAVEL-IN\nRerankID: \nPartifulID: 1N6CtiCpYquktoTh5NUm\nWalk 4 min to 23 St (A/C/E); subway 11 min; walk 5 min from Times Sq-42 St (GS); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: Building secure AI for your data: DeepFellow Demo + Q&A -> 1155 6th Ave, New York, NY 10036 ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/1N6CtiCpYquktoTh5NUm"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4444] [PENDING] The Future of Coding Agents and IDE", start date:my makeDate(3, 14, 0), end date:my makeDate(3, 15, 0), location:"1155 6th Ave, New York, NY 10036", description:"TechWeekID: TW-4444\nCalendarBlockID: TW-4444-SCHEDULE\nRerankID: 4444\nPartifulID: 1N6CtiCpYquktoTh5NUm\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=2; plusOne=TBD.\nRSVP status: applied\nCategory: primary\nVenue basis: 1155 6th Ave, New York, NY 10036 (manual_exact_manhattan)\nRank/tier/score: 27 / A / 72\nURL: https://partiful.com/e/1N6CtiCpYquktoTh5NUm"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5529-TRAVEL-IN] The Future of Coding Agents and IDE -> Fireside chat - When coding agents are the user?", start date:my makeDate(3, 15, 40), end date:my makeDate(3, 16, 0), location:"The Future of Coding Agents and IDE -> New York, NY", description:"TechWeekID: TW-5529\nCalendarBlockID: TW-5529-TRAVEL-IN\nRerankID: \nPartifulID: E8NhJNHWGhMetLlrFvQ7\nWalk approx 20 min / 1595 m using OSM-geocoded points.\nRSVP status: registered\nCategory: travel\nVenue basis: The Future of Coding Agents and IDE -> New York, NY ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/E8NhJNHWGhMetLlrFvQ7"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5529] [REG] Fireside chat - When coding agents are the user?", start date:my makeDate(3, 16, 0), end date:my makeDate(3, 17, 15), location:"New York, NY", description:"TechWeekID: TW-5529\nCalendarBlockID: TW-5529-SCHEDULE\nRerankID: 5529\nPartifulID: E8NhJNHWGhMetLlrFvQ7\nRegistered; monitor for updates Submitted via Partiful API; rsvpStatus=GOING; count=2; plusOne=TBD.\nRSVP status: registered\nCategory: primary\nVenue basis: 28th Street and Broadway, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 15 / S / 81\nURL: https://partiful.com/e/E8NhJNHWGhMetLlrFvQ7"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4664-TRAVEL-IN] Fireside chat - When coding agents are the user? -> MCP in the Wild: Panel & Night of Networking", start date:my makeDate(3, 17, 40), end date:my makeDate(3, 18, 0), location:"Fireside chat - When coding agents are the user? -> East Village", description:"TechWeekID: TW-4664\nCalendarBlockID: TW-4664-TRAVEL-IN\nRerankID: \nPartifulID: 6ZuudQBBZXcMNjdMynJ2\nWalk 1 min to 28 St (N/Q/R/W); subway 13 min; walk 1 min from Astor Pl (4/6); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: Fireside chat - When coding agents are the user? -> East Village ()\nRank/tier/score:  /  / \nURL: https://partiful.com/events/6ZuudQBBZXcMNjdMynJ2"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-4664] [PENDING] MCP in the Wild: Panel & Night of Networking", start date:my makeDate(3, 18, 0), end date:my makeDate(3, 20, 30), location:"East Village", description:"TechWeekID: TW-4664\nCalendarBlockID: TW-4664-SCHEDULE\nRerankID: 4664\nPartifulID: 6ZuudQBBZXcMNjdMynJ2\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: primary\nVenue basis: Astor Place, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 58 / A / 63\nURL: https://partiful.com/events/6ZuudQBBZXcMNjdMynJ2"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-20260603-TRAVEL-HOME] MCP in the Wild: Panel & Night of Networking -> FiDi home base", start date:my makeDate(3, 20, 30), end date:my makeDate(3, 20, 50), location:"MCP in the Wild: Panel & Night of Networking -> FiDi home base", description:"TechWeekID: TW-4664\nCalendarBlockID: TW-20260603-TRAVEL-HOME\nRerankID: \nPartifulID: 6ZuudQBBZXcMNjdMynJ2\nWalk 1 min to Astor Pl (4/6); subway 14 min; walk 0 min from Wall St (2/3); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: MCP in the Wild: Panel & Night of Networking -> FiDi home base ()\nRank/tier/score:  /  / \nURL: https://partiful.com/events/6ZuudQBBZXcMNjdMynJ2"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5372-TRAVEL-IN] FiDi home base -> Shipping Faster with AI Coding Agents: What's Working and What's Not", start date:my makeDate(4, 15, 36), end date:my makeDate(4, 16, 0), location:"FiDi home base -> New York, NY", description:"TechWeekID: TW-5372\nCalendarBlockID: TW-5372-TRAVEL-IN\nRerankID: \nPartifulID: 5K5c4eODrGPKME7or20H\nWalk 0 min to Wall St (2/3); subway 19 min; walk 0 min from Prince St (N/Q/R/W); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: FiDi home base -> New York, NY ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/5K5c4eODrGPKME7or20H"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5372] [PENDING] Shipping Faster with AI Coding Agents: What's Working and What's Not", start date:my makeDate(4, 16, 0), end date:my makeDate(4, 18, 51), location:"New York, NY", description:"TechWeekID: TW-5372\nCalendarBlockID: TW-5372-SCHEDULE\nRerankID: 5372\nPartifulID: 5K5c4eODrGPKME7or20H\nLeave early if needed so you can make the registered 19:00 Stop Making AI Guess event. Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none. Route calendar shortens this from the event's scheduled 19:00 end; leave 9 min early for transit.\nRSVP status: applied\nCategory: primary\nVenue basis: Spring St and Broadway, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 4 / S / 100\nURL: https://partiful.com/e/5K5c4eODrGPKME7or20H"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5114-TRAVEL-IN] Shipping Faster with AI Coding Agents: What's Working and What's Not -> Stop Making AI Guess: When Your Codebase Becomes the Spec", start date:my makeDate(4, 18, 51), end date:my makeDate(4, 19, 0), location:"Shipping Faster with AI Coding Agents: What's Working and What's Not -> Union Square", description:"TechWeekID: TW-5114\nCalendarBlockID: TW-5114-TRAVEL-IN\nRerankID: \nPartifulID: X0u5GrmzvIUTrjoAOgVm\nLeave previous event 9 min before its scheduled end.\nWalk 0 min to Prince St (N/Q/R/W); subway 4 min; walk 0 min from 14 St-Union Sq (N/Q/R/W); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: Shipping Faster with AI Coding Agents: What's Working and What's Not -> Union Square ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/X0u5GrmzvIUTrjoAOgVm"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5114] [REG] Stop Making AI Guess: When Your Codebase Becomes the Spec", start date:my makeDate(4, 19, 0), end date:my makeDate(4, 20, 45), location:"Union Square", description:"TechWeekID: TW-5114\nCalendarBlockID: TW-5114-SCHEDULE\nRerankID: 5114\nPartifulID: X0u5GrmzvIUTrjoAOgVm\nRegistered direct. This is the Thursday anchor unless a substantially better curated dinner approves. Registered; monitor for updates Submitted via Partiful API; rsvpStatus=GOING; count=2; plusOne=TBD.\nRSVP status: registered\nCategory: apply\nVenue basis: Union Square, Manhattan, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 21 / S / 76\nURL: https://partiful.com/e/X0u5GrmzvIUTrjoAOgVm"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-20260604-TRAVEL-HOME] Stop Making AI Guess: When Your Codebase Becomes the Spec -> FiDi home base", start date:my makeDate(4, 20, 45), end date:my makeDate(4, 21, 3), location:"Stop Making AI Guess: When Your Codebase Becomes the Spec -> FiDi home base", description:"TechWeekID: TW-5114\nCalendarBlockID: TW-20260604-TRAVEL-HOME\nRerankID: \nPartifulID: X0u5GrmzvIUTrjoAOgVm\nWalk 0 min to 14 St-Union Sq (N/Q/R/W); subway 13 min; walk 0 min from Wall St (2/3); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: Stop Making AI Guess: When Your Codebase Becomes the Spec -> FiDi home base ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/X0u5GrmzvIUTrjoAOgVm"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5722-TRAVEL-IN] FiDi home base -> Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration", start date:my makeDate(5, 16, 22), end date:my makeDate(5, 17, 0), location:"FiDi home base -> Union Square", description:"TechWeekID: TW-5722\nCalendarBlockID: TW-5722-TRAVEL-IN\nRerankID: \nPartifulID: jkjGahQgmH9PLIxjfTFt\nWalk 0 min to Wall St (2/3); subway 29 min; walk 4 min from 14 St-Union Sq (N/Q/R/W); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: FiDi home base -> Union Square ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/jkjGahQgmH9PLIxjfTFt"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-5722] [PENDING] Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration", start date:my makeDate(5, 17, 0), end date:my makeDate(5, 20, 0), location:"Union Square", description:"TechWeekID: TW-5722\nCalendarBlockID: TW-5722-SCHEDULE\nRerankID: 5722\nPartifulID: jkjGahQgmH9PLIxjfTFt\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: primary\nVenue basis: Union Square Park, 201 Park Ave S, New York, NY 10003 (exact_from_partiful_maps)\nRank/tier/score: 45 / A / 64\nURL: https://partiful.com/e/jkjGahQgmH9PLIxjfTFt"}
	make new event at end of events of scheduleCal with properties {summary:"[TW-20260605-TRAVEL-HOME] Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration -> FiDi home base", start date:my makeDate(5, 20, 0), end date:my makeDate(5, 20, 22), location:"Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration -> FiDi home base", description:"TechWeekID: TW-5722\nCalendarBlockID: TW-20260605-TRAVEL-HOME\nRerankID: \nPartifulID: jkjGahQgmH9PLIxjfTFt\nWalk 4 min to 14 St-Union Sq (N/Q/R/W); subway 13 min; walk 0 min from Wall St (2/3); includes 5 min buffer.\nRSVP status: registered\nCategory: travel\nVenue basis: Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration -> FiDi home base ()\nRank/tier/score:  /  / \nURL: https://partiful.com/e/jkjGahQgmH9PLIxjfTFt"}

	-- Reference layer excludes events already present on the operational route to avoid duplicate rendering.
	make new event at end of events of referenceCal with properties {summary:"[TW-5110] [PENDING BACKUP] Slack x Amplitude: AI at work", start date:my makeDate(1, 17, 0), end date:my makeDate(1, 18, 30), location:"Tribeca", description:"TechWeekID: TW-5110\nCalendarBlockID: TW-5110-REFERENCE\nRerankID: 5110\nPartifulID: dmFBKIxzn2LdFmktqas8\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: backup\nVenue basis: Fabrik, 16 Vestry St, New York, NY 10013 (exact_from_partiful_maps)\nRank/tier/score: 180 / B / 53\nURL: https://partiful.com/e/dmFBKIxzn2LdFmktqas8"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5962] [REG BACKUP] Software for Hardware: The Tools Powering Robotics & Embodied AI", start date:my makeDate(1, 18, 0), end date:my makeDate(1, 21, 0), location:"Civic Hall, 124 E 14th St 2nd Floor, New York, NY", description:"TechWeekID: TW-5962\nCalendarBlockID: TW-5962-REFERENCE\nRerankID: 5962\nPartifulID: 09a0qPKv0cSOIOSGxjTQ\nPartiful registered only. Secondary Luma checkout is $20 and was explicitly skipped. Partiful registered; skip paid Luma checkout Submitted via Partiful API; rsvpStatus=GOING; count=1; plusOne=none. Secondary Luma link requires $20 paid ticket; user explicitly said do not complete checkout.\nRSVP status: registered\nCategory: backup\nVenue basis: Civic Hall, 124 E 14th St, New York, NY 10003 (exact_from_partiful_maps)\nRank/tier/score: 13 / S / 86\nURL: https://partiful.com/e/09a0qPKv0cSOIOSGxjTQ"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4200] [REG BACKUP] NYC B2B: AI Founders & Investors Mixer", start date:my makeDate(1, 18, 30), end date:my makeDate(1, 20, 0), location:"Skinos, 123 Washington St, New York, NY", description:"TechWeekID: TW-4200\nCalendarBlockID: TW-4200-REFERENCE\nRerankID: 4200\nPartifulID: oQvmxTsHOVayx47ok3li\nRegistered backup near FiDi. Use if Open Source Must Win is not approved or is too low signal in practice. Registered; monitor for updates Submitted via Partiful API; rsvpStatus=GOING; count=2; plusOne=TBD.\nRSVP status: registered\nCategory: backup\nVenue basis: Skinos, 123 Washington St, New York, NY (exact_from_signup_status)\nRank/tier/score: 169 / B / 54\nURL: https://partiful.com/e/oQvmxTsHOVayx47ok3li?c=0hT1WkMm"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4522] [WAITLIST BACKUP] Operating MCP", start date:my makeDate(2, 16, 0), end date:my makeDate(2, 19, 0), location:"TBC", description:"TechWeekID: TW-4522\nCalendarBlockID: TW-4522-REFERENCE\nRerankID: 4522\nPartifulID: 5vHvRPI0VlMQwOmQadCN\nMonitor waitlist / host approval Submitted via Partiful API; rsvpStatus=WAITLIST; count=2; plusOne=TBD.\nRSVP status: waitlisted\nCategory: backup\nVenue basis: Bryant Park, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 7 / S / 98\nURL: https://partiful.com/e/5vHvRPI0VlMQwOmQadCN"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4224] [PENDING BACKUP] WorkOS + Postman Agents & APIs Demo Night", start date:my makeDate(2, 17, 30), end date:my makeDate(2, 19, 0), location:"56 Greene Street, 4th Floor New York, NY 10012", description:"TechWeekID: TW-4224\nCalendarBlockID: TW-4224-REFERENCE\nRerankID: 4224\nPartifulID: XqIBMZmB4oubCZWFP2Sl\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: backup\nVenue basis: Spring St and Broadway, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 217 / B / 51\nURL: https://partiful.com/e/XqIBMZmB4oubCZWFP2Sl"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5415] [PENDING BACKUP] AI, Algorithms & Liability: What Tech Leaders & Creators Need to Know", start date:my makeDate(2, 17, 30), end date:my makeDate(2, 19, 0), location:"One Battery Park Plaza, 7th Floor New York, NY 10004", description:"TechWeekID: TW-5415\nCalendarBlockID: TW-5415-REFERENCE\nRerankID: 5415\nPartifulID: UBrZopzqpRwbn6Qk0npO\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: backup\nVenue basis: Wall St, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 72 / B / 58\nURL: https://partiful.com/e/UBrZopzqpRwbn6Qk0npO?c=4IfpVNvT"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5437] [PENDING CURATED] Enterprise AI Happy Hour", start date:my makeDate(2, 18, 0), end date:my makeDate(2, 19, 30), location:"SoHo", description:"TechWeekID: TW-5437\nCalendarBlockID: TW-5437-REFERENCE\nRerankID: 5437\nPartifulID: FSzOO6xPn11iqxVdtQ9j\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: apply\nVenue basis: Spring St and Broadway, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 2 / S / 100\nURL: https://partiful.com/e/FSzOO6xPn11iqxVdtQ9j?"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5925] [PENDING BACKUP] Cloudflare + Shopify: Build for the Agent Era", start date:my makeDate(2, 18, 0), end date:my makeDate(2, 20, 0), location:"SoHo", description:"TechWeekID: TW-5925\nCalendarBlockID: TW-5925-REFERENCE\nRerankID: 5925\nPartifulID: jytNb4IdG0HxwJnqDSgf\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: backup\nVenue basis: Shopify New York, 131 Greene St, New York, NY 10012 (exact_from_partiful_maps)\nRank/tier/score: 23 / S / 75\nURL: https://partiful.com/e/jytNb4IdG0HxwJnqDSgf"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5820] [PENDING CURATED] Anthropic Founder Salon: Inside the AI-Native Era", start date:my makeDate(3, 13, 30), end date:my makeDate(3, 17, 0), location:"New York, NY - Chelsea neighborhood (venue details upon confirmation)", description:"TechWeekID: TW-5820\nCalendarBlockID: TW-5820-REFERENCE\nRerankID: 5820\nPartifulID: titPml1Nw0DKwGl9B6CF\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: apply\nVenue basis: 23rd Street and 8th Avenue, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 9 / S / 94\nURL: https://partiful.com/e/titPml1Nw0DKwGl9B6CF"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4719] [PENDING CURATED] Agent Harnesses: What It Takes to Make AI Agents Work in the Enterprise", start date:my makeDate(3, 16, 0), end date:my makeDate(3, 21, 0), location:"Union Square", description:"TechWeekID: TW-4719\nCalendarBlockID: TW-4719-REFERENCE\nRerankID: 4719\nPartifulID: 2NP0rZW8BmdGAGUOEhGP\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: apply\nVenue basis: Union Square W, New York, NY 10003 (exact_from_partiful_maps)\nRank/tier/score: 8 / S / 97\nURL: https://partiful.com/e/2NP0rZW8BmdGAGUOEhGP?f=1"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4778] [PENDING CURATED] The CTO Mixer: Humanizing Tech | Happy Hour", start date:my makeDate(3, 17, 30), end date:my makeDate(3, 19, 30), location:"Midtown, Manhattan, New York, NY", description:"TechWeekID: TW-4778\nCalendarBlockID: TW-4778-REFERENCE\nRerankID: 4778\nPartifulID: h1hGv0PkskcagJOv5M9K\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: apply\nVenue basis: Astor Place, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 6 / S / 100\nURL: https://partiful.com/e/h1hGv0PkskcagJOv5M9K"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5693] [PENDING BACKUP] Camp AI: Agents at Work", start date:my makeDate(3, 17, 30), end date:my makeDate(3, 19, 30), location:"620 8th Ave, New York, NY 10018", description:"TechWeekID: TW-5693\nCalendarBlockID: TW-5693-REFERENCE\nRerankID: 5693\nPartifulID: Fp5STyPH0McEt0awlWFD\nWait for host approval Submitted via Partiful API after user confirmed age 21+; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: backup\nVenue basis: 620 8th Ave, New York, NY 10018 (manual_exact_manhattan)\nRank/tier/score: 19 / S / 78\nURL: https://partiful.com/e/Fp5STyPH0McEt0awlWFD"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4197] [PENDING CURATED] The Tech Leaders Suite", start date:my makeDate(3, 19, 0), end date:my makeDate(3, 21, 0), location:"Brooklyn", description:"TechWeekID: TW-4197\nCalendarBlockID: TW-4197-REFERENCE\nRerankID: 4197\nPartifulID: UhyErPPxuo2vELIutdGj\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: apply\nVenue basis: Barclays Center, Brooklyn, NY (approx_neighborhood_hidden)\nRank/tier/score: 5 / S / 100\nURL: https://partiful.com/e/UhyErPPxuo2vELIutdGj?"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4191] [PENDING BACKUP] Agents at Scale", start date:my makeDate(4, 18, 0), end date:my makeDate(4, 20, 0), location:"SoHo", description:"TechWeekID: TW-4191\nCalendarBlockID: TW-4191-REFERENCE\nRerankID: 4191\nPartifulID: 6BlGFmwIdpyndqyLYS2v\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: backup\nVenue basis: Spring St and Broadway, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 10 / S / 93\nURL: https://partiful.com/e/6BlGFmwIdpyndqyLYS2v?c=bv5YqCoL"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4826] [PENDING BACKUP] Steal These AI Workflows: Live Demos from NYC's Top AI Builders", start date:my makeDate(4, 18, 0), end date:my makeDate(4, 19, 30), location:"Union Square", description:"TechWeekID: TW-4826\nCalendarBlockID: TW-4826-REFERENCE\nRerankID: 4826\nPartifulID: sGvp4VIr3KrGqRoWCKhV\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none. Secondary Google Form submitted for UbiquityOS Accolades build demo.\nRSVP status: applied\nCategory: backup\nVenue basis: Union Square E, New York, NY 10003 (exact_from_partiful_maps)\nRank/tier/score: 34 / A / 66\nURL: https://partiful.com/e/sGvp4VIr3KrGqRoWCKhV"}
	make new event at end of events of referenceCal with properties {summary:"[TW-4183] [PENDING CURATED] Engineering Leaders After Hours: A Build and Ship Cocktail Competition", start date:my makeDate(4, 18, 30), end date:my makeDate(4, 21, 30), location:"BarChef NYC, 21 W 35th St,, New York, NY", description:"TechWeekID: TW-4183\nCalendarBlockID: TW-4183-REFERENCE\nRerankID: 4183\nPartifulID: bETmU06uq4TtORng6I1l\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: apply\nVenue basis: BarChef NYC, 21 W 35th St,, New York, NY (exact_from_signup_status)\nRank/tier/score: 20 / S / 78\nURL: https://partiful.com/e/bETmU06uq4TtORng6I1l"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5204] [PENDING BACKUP] From Prediction Markets to Predictive Intelligence Systems", start date:my makeDate(4, 19, 0), end date:my makeDate(4, 20, 30), location:"Financial District", description:"TechWeekID: TW-5204\nCalendarBlockID: TW-5204-REFERENCE\nRerankID: 5204\nPartifulID: eSldi3iNIvAVo9utdd8S\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: backup\nVenue basis: Wall St, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 89 / B / 57\nURL: https://partiful.com/e/eSldi3iNIvAVo9utdd8S"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5231] [PENDING CURATED] AI BUILDERS DINNER", start date:my makeDate(4, 19, 0), end date:my makeDate(4, 21, 0), location:"Flatiron, Manhattan, New York, NY", description:"TechWeekID: TW-5231\nCalendarBlockID: TW-5231-REFERENCE\nRerankID: 5231\nPartifulID: idltitmjA4ZzL9IuK0Y6\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: apply\nVenue basis: 23rd Street and Broadway, New York, NY (approx_neighborhood_hidden)\nRank/tier/score: 11 / S / 90\nURL: https://partiful.com/e/idltitmjA4ZzL9IuK0Y6"}
	make new event at end of events of referenceCal with properties {summary:"[TW-5207] [PENDING BACKUP] Free Phos, Real Convos. Agents in your DMs", start date:my makeDate(4, 20, 0), end date:my makeDate(4, 21, 30), location:"Flatiron", description:"TechWeekID: TW-5207\nCalendarBlockID: TW-5207-REFERENCE\nRerankID: 5207\nPartifulID: ed2EFWip0do9OuYmVPZI\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none. Required follow questions answered truthfully as Not yet.\nRSVP status: applied\nCategory: backup\nVenue basis: Pho Dragon Restaurant, 47 W 14th St, New York, NY 10011 (exact_from_partiful_maps)\nRank/tier/score: 18 / S / 79\nURL: https://partiful.com/e/ed2EFWip0do9OuYmVPZI"}
	make new event at end of events of referenceCal with properties {summary:"[TW-250] [PENDING CURATED] YouCode AI Salon", start date:my makeDate(5, 18, 0), end date:my makeDate(5, 21, 0), location:"New York, NY", description:"TechWeekID: TW-250\nCalendarBlockID: TW-250-REFERENCE\nRerankID: 250\nPartifulID: kvGpuFMeACW7ZWPYtxTP\nWait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.\nRSVP status: applied\nCategory: apply\nVenue basis: Barclays Center, Brooklyn, NY (approx_neighborhood_hidden)\nRank/tier/score: 26 / A / 73\nURL: https://partiful.com/e/kvGpuFMeACW7ZWPYtxTP"}
end tell
end timeout
