-- Generated by scripts/build_signed_up_calendar.ts
tell application "Calendar"
	set scheduleName to "NY Tech Week 2026 - Schedule"
	set referenceName to "NY Tech Week 2026 - All RSVPs"
	if not (exists calendar scheduleName) then make new calendar with properties {name:scheduleName}
	if not (exists calendar referenceName) then make new calendar with properties {name:referenceName}
	set scheduleCal to calendar scheduleName
	set referenceCal to calendar referenceName
	make new event at end of events of scheduleCal with properties {summary:"Sleep: 8 hours", start date:date "2026-06-01 03:13", end date:date "2026-06-01 11:13", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260601-SLEEP
RerankID:
PartifulID:
Staggered late sleep block; night-to-night bedtime shift stays within 30 minutes.
RSVP status: registered
Category: sleep
Venue basis: 15 Cliff Street, New York, NY 10038 (sleep_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Lunch / reset", start date:date "2026-06-01 12:15", end date:date "2026-06-01 13:15", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260601-MEAL-LUNCH
RerankID:
PartifulID:
One-hour food buffer before leaving for the first event.
RSVP status: registered
Category: meal
Venue basis: 15 Cliff Street, New York, NY 10038 (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: 15 Cliff Street, New York, NY 10038 -> Beyond the Spec Masterclass: Engineering in the Age of Agents", start date:date "2026-06-01 13:21", end date:date "2026-06-01 14:00", location:"15 Cliff Street, New York, NY 10038 -> Flatiron", description:"TechWeekID: TW-6408
CalendarBlockID: TW-6408-TRAVEL-IN
RerankID:
PartifulID: FHiuNwzr13e3YBI4ssUX
Walk 3 min to Fulton St (2/3); subway 29 min; walk 2 min from 23 St-Baruch College (4/6); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: 15 Cliff Street, New York, NY 10038 -> Flatiron ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7084297%2C-74.0056635&destination=40.7408301%2C-73.9868072&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/FHiuNwzr13e3YBI4ssUX"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] Beyond the Spec Masterclass: Engineering in the Age of Agents", start date:date "2026-06-01 14:00", end date:date "2026-06-01 15:00", location:"Flatiron", description:"TechWeekID: TW-6408
CalendarBlockID: TW-6408-SCHEDULE
RerankID: 6408
PartifulID: FHiuNwzr13e3YBI4ssUX
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use the agent/spec theme. Say you are studying how specs, PRs, and Slack context survive agentic workflows.
Ask: When an agent touches a ticket, what artifact proves who shaped the outcome?
Listen for: Specs as source of truth, issue quality, review quality, manager trust, missing context.
Follow-up: Ask for 20 minutes with whoever owns engineering process or agent adoption.
RSVP status: applied
Category: primary
Venue basis: IBM One Madison Avenue, 1 Madison Ave,, New York, NY 10010 (exact_from_partiful_maps)
Google Maps: https://www.google.com/maps/search/?api=1&query=IBM+One+Madison+Avenue%2C+1+Madison+Ave%2C%2C+New+York%2C+NY+10010
Rank/tier/score: 24 / S / 74
URL: https://partiful.com/e/FHiuNwzr13e3YBI4ssUX"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: Beyond the Spec Masterclass: Engineering in the Age of Agents -> From Vibe Coding to AI-Driven Development", start date:date "2026-06-01 15:50", end date:date "2026-06-01 16:00", location:"Beyond the Spec Masterclass: Engineering in the Age of Agents -> WeWork, 135 Madison Ave, New York, NY", description:"TechWeekID: TW-44
CalendarBlockID: TW-44-TRAVEL-IN
RerankID:
PartifulID: xowd9F3kB7mPFN1luUwY
Walk approx 10 min / 767 m using OSM-geocoded points.
RSVP status: registered
Category: travel
Venue basis: Beyond the Spec Masterclass: Engineering in the Age of Agents -> WeWork, 135 Madison Ave, New York, NY ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7408301%2C-73.9868072&destination=40.7459513%2C-73.984086&travelmode=walking
Rank/tier/score:  /  /
URL: https://partiful.com/e/xowd9F3kB7mPFN1luUwY"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] From Vibe Coding to AI-Driven Development", start date:date "2026-06-01 16:00", end date:date "2026-06-01 17:00", location:"WeWork, 135 Madison Ave, New York, NY", description:"TechWeekID: TW-44
CalendarBlockID: TW-44-SCHEDULE
RerankID: 44
PartifulID: xowd9F3kB7mPFN1luUwY
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=2; plusOne=TBD.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Frame vibe coding as a team-process problem, not a solo productivity trick.
Ask: What breaks when vibe coding becomes team development across reviews, specs, and handoffs?
Listen for: Review bottlenecks, low-trust AI output, unclear ownership, managers losing visibility.
Follow-up: Send a short write-up on contribution evidence for AI-assisted teams.
RSVP status: applied
Category: primary
Venue basis: WeWork, 135 Madison Ave, New York, NY (exact_from_signup_status)
Google Maps: https://www.google.com/maps/search/?api=1&query=WeWork%2C+135+Madison+Ave%2C+New+York%2C+NY
Rank/tier/score: 29 / A / 71
URL: https://partiful.com/e/xowd9F3kB7mPFN1luUwY"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: From Vibe Coding to AI-Driven Development -> Open Source Must Win", start date:date "2026-06-01 17:28", end date:date "2026-06-01 18:00", location:"From Vibe Coding to AI-Driven Development -> New York, NY", description:"TechWeekID: TW-5978
CalendarBlockID: TW-5978-TRAVEL-IN
RerankID:
PartifulID: OF1vP5L8dtXKRtInyWKs
Walk 3 min to 33 St (4/6); subway 23 min; walk 1 min from Delancey St-Essex St (F); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: From Vibe Coding to AI-Driven Development -> New York, NY ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7459513%2C-73.984086&destination=40.718618%2C-73.988136&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/OF1vP5L8dtXKRtInyWKs?c=s6u4EYds"}
	make new event at end of events of scheduleCal with properties {summary:"[REG] Open Source Must Win", start date:date "2026-06-01 18:00", end date:date "2026-06-01 21:00", location:"New York, NY", description:"TechWeekID: TW-5978
CalendarBlockID: TW-5978-SCHEDULE
RerankID: 5978
PartifulID: OF1vP5L8dtXKRtInyWKs
If this is not approved, use registered backup NYC B2B at Skinos instead. On the list; monitor for updates Submitted via Partiful API; Partiful live sync 2026-05-12: rsvpStatus=APPROVED; count=2; plusOne=TBD; approved 2026-05-10 11:16 ET.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Open-source rooms should hear the maintainer-labor angle first.
Ask: How do you credit review, triage, specs, and maintainer work that never becomes a commit?
Listen for: Contributor rewards, bounty systems, maintainer burnout, attribution disputes.
Follow-up: Ask for intros to maintainers, DevRel leads, or teams running contributor programs.
RSVP status: registered
Category: primary
Venue basis: Delancey St Essex St, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Delancey+St+Essex+St%2C+New+York%2C+NY
Rank/tier/score: 37 / A / 64
URL: https://partiful.com/e/OF1vP5L8dtXKRtInyWKs?c=s6u4EYds"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Dinner after Open Source Must Win", start date:date "2026-06-01 21:00", end date:date "2026-06-01 22:00", location:"Lower East Side", description:"TechWeekID:
CalendarBlockID: TW-20260601-MEAL-DINNER
RerankID:
PartifulID:
One-hour meal buffer before heading home.
RSVP status: registered
Category: meal
Venue basis: Lower East Side (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=Lower+East+Side%2C+New+York%2C+NY
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: Open Source Must Win -> 15 Cliff Street, New York, NY 10038", start date:date "2026-06-01 22:00", end date:date "2026-06-01 22:30", location:"Open Source Must Win -> 15 Cliff Street, New York, NY 10038", description:"TechWeekID: TW-5978
CalendarBlockID: TW-20260601-TRAVEL-HOME
RerankID:
PartifulID: OF1vP5L8dtXKRtInyWKs
Walk approx 30 min / 2327 m using OSM-geocoded points.
RSVP status: registered
Category: travel
Venue basis: Open Source Must Win -> 15 Cliff Street, New York, NY 10038 ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.718618%2C-73.988136&destination=40.7084297%2C-74.0056635&travelmode=walking
Rank/tier/score:  /  /
URL: https://partiful.com/e/OF1vP5L8dtXKRtInyWKs?c=s6u4EYds"}
	make new event at end of events of scheduleCal with properties {summary:"Sleep: 8 hours", start date:date "2026-06-02 02:43", end date:date "2026-06-02 10:43", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260602-SLEEP
RerankID:
PartifulID:
Staggered late sleep block; wake leaves 30 minutes before the first travel block.
RSVP status: registered
Category: sleep
Venue basis: 15 Cliff Street, New York, NY 10038 (sleep_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: 15 Cliff Street, New York, NY 10038 -> How to Write a Book on AI in Enterprise SDLC While Patterns Keep Changing", start date:date "2026-06-02 11:12", end date:date "2026-06-02 12:00", location:"15 Cliff Street, New York, NY 10038 -> New York, NY", description:"TechWeekID: TW-4551
CalendarBlockID: TW-4551-TRAVEL-IN
RerankID:
PartifulID: M7pXmV8sOXT11yHb9pKw
Walk 3 min to Fulton St (2/3); subway 38 min; walk 2 min from 42 St-Bryant Pk (B/D/F/M); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: 15 Cliff Street, New York, NY 10038 -> New York, NY ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7084297%2C-74.0056635&destination=40.753751%2C-73.983543&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/M7pXmV8sOXT11yHb9pKw"}
	make new event at end of events of scheduleCal with properties {summary:"[REG] How to Write a Book on AI in Enterprise SDLC While Patterns Keep Changing", start date:date "2026-06-02 12:00", end date:date "2026-06-02 13:45", location:"New York, NY", description:"TechWeekID: TW-4551
CalendarBlockID: TW-4551-SCHEDULE
RerankID: 4551
PartifulID: M7pXmV8sOXT11yHb9pKw
On the list; monitor for updates Submitted via Partiful API; Partiful live sync 2026-05-12: rsvpStatus=APPROVED; count=1; plusOne=none; approved 2026-05-11 10:21 ET.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use enterprise SDLC language: trustworthy artifacts, change control, and evidence trails.
Ask: Which engineering artifacts stay reliable when AI changes how teams plan, review, and ship?
Listen for: Auditability, manager reports, PR review evidence, specs scattered across tools.
Follow-up: Ask to compare their SDLC reporting process with an Accolades evidence report.
RSVP status: registered
Category: primary
Venue basis: Bryant Park, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Bryant+Park%2C+New+York%2C+NY
Rank/tier/score: 33 / A / 68
URL: https://partiful.com/e/M7pXmV8sOXT11yHb9pKw"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Lunch / reset", start date:date "2026-06-02 13:45", end date:date "2026-06-02 14:45", location:"Midtown", description:"TechWeekID:
CalendarBlockID: TW-20260602-MEAL-LUNCH
RerankID:
PartifulID:
One-hour break after the Enterprise SDLC session.
RSVP status: registered
Category: meal
Venue basis: Midtown (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=Midtown+Manhattan%2C+New+York%2C+NY
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] From Copilot to Control Plane - Visdom", start date:date "2026-06-02 16:00", end date:date "2026-06-02 17:30", location:"Midtown", description:"TechWeekID: TW-4341
CalendarBlockID: TW-4341-SCHEDULE
RerankID: 4341
PartifulID: bn5h1g13xzOV6R5XkLaE
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: This is the highest-priority CTO/platform room. Lead with the control-plane problem.
Ask: What should managers measure once copilots are part of every development workflow?
Listen for: CTO/VP Eng pain, platform ownership, productivity reporting, GitHub/code review evidence.
Follow-up: Push for a concrete post-Tech Week call if they own DevEx, platform, or engineering metrics.
RSVP status: applied
Category: primary
Venue basis: Bryant Park, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Bryant+Park%2C+New+York%2C+NY
Rank/tier/score: 1 / S / 100
URL: https://partiful.com/e/bn5h1g13xzOV6R5XkLaE"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: From Copilot to Control Plane - Visdom -> Future of DevEx", start date:date "2026-06-02 17:36", end date:date "2026-06-02 18:00", location:"From Copilot to Control Plane - Visdom -> SoHo", description:"TechWeekID: TW-4161
CalendarBlockID: TW-4161-TRAVEL-IN
RerankID:
PartifulID: 7DYGSiY1WUuRSvEnD5gp
Walk 2 min to 42 St-Bryant Pk (B/D/F/M); subway 17 min; walk 0 min from Prince St (N/Q/R/W); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: From Copilot to Control Plane - Visdom -> SoHo ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.753751%2C-73.983543&destination=40.724329%2C-73.997702&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/7DYGSiY1WUuRSvEnD5gp?c=aQ_TnSt9"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] Future of DevEx", start date:date "2026-06-02 18:00", end date:date "2026-06-02 21:00", location:"SoHo", description:"TechWeekID: TW-4161
CalendarBlockID: TW-4161-SCHEDULE
RerankID: 4161
PartifulID: 7DYGSiY1WUuRSvEnD5gp
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use DevEx language and avoid sounding like HR analytics.
Ask: Where does DevEx stop being tooling and start being contribution evidence?
Listen for: Internal developer platforms, friction measurement, review quality, invisible glue work.
Follow-up: Ask who owns DevEx metrics and whether source-linked contribution evidence would help.
RSVP status: applied
Category: primary
Venue basis: Spring St and Broadway, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Spring+St+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: 3 / S / 100
URL: https://partiful.com/e/7DYGSiY1WUuRSvEnD5gp?c=aQ_TnSt9"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Dinner after Future of DevEx", start date:date "2026-06-02 21:00", end date:date "2026-06-02 22:00", location:"SoHo", description:"TechWeekID:
CalendarBlockID: TW-20260602-MEAL-DINNER
RerankID:
PartifulID:
One-hour meal buffer before heading home.
RSVP status: registered
Category: meal
Venue basis: SoHo (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=SoHo%2C+New+York%2C+NY
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: Future of DevEx -> 15 Cliff Street, New York, NY 10038", start date:date "2026-06-02 22:00", end date:date "2026-06-02 22:21", location:"Future of DevEx -> 15 Cliff Street, New York, NY 10038", description:"TechWeekID: TW-4161
CalendarBlockID: TW-20260602-TRAVEL-HOME
RerankID:
PartifulID: 7DYGSiY1WUuRSvEnD5gp
Walk 0 min to Prince St (N/Q/R/W); subway 13 min; walk 3 min from Fulton St (2/3); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: Future of DevEx -> 15 Cliff Street, New York, NY 10038 ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.724329%2C-73.997702&destination=40.7084297%2C-74.0056635&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/7DYGSiY1WUuRSvEnD5gp?c=aQ_TnSt9"}
	make new event at end of events of scheduleCal with properties {summary:"Sleep: 8 hours", start date:date "2026-06-03 02:45", end date:date "2026-06-03 10:45", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260603-SLEEP
RerankID:
PartifulID:
Staggered late sleep block; wake lands on the quick breakfast/lunch block.
RSVP status: registered
Category: sleep
Venue basis: 15 Cliff Street, New York, NY 10038 (sleep_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Quick breakfast / lunch before dense Wednesday", start date:date "2026-06-03 10:45", end date:date "2026-06-03 11:15", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260603-MEAL-LUNCH
RerankID:
PartifulID:
Hectic-day 30-minute food buffer before the midday run starts.
RSVP status: registered
Category: meal
Venue basis: 15 Cliff Street, New York, NY 10038 (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: 15 Cliff Street, New York, NY 10038 -> Building secure AI for your data: DeepFellow Demo + Q&A", start date:date "2026-06-03 11:28", end date:date "2026-06-03 12:00", location:"15 Cliff Street, New York, NY 10038 -> Chelsea", description:"TechWeekID: TW-5889
CalendarBlockID: TW-5889-TRAVEL-IN
RerankID:
PartifulID: 4HvzWY1VZlHgK21fMBUz
Walk 3 min to Fulton St (2/3); subway 20 min; walk 4 min from 23 St (A/C/E); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: 15 Cliff Street, New York, NY 10038 -> Chelsea ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7084297%2C-74.0056635&destination=40.744081%2C-73.999562&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/4HvzWY1VZlHgK21fMBUz?c=g5NbnbjN"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] Building secure AI for your data: DeepFellow Demo + Q&A", start date:date "2026-06-03 12:00", end date:date "2026-06-03 13:15", location:"Chelsea", description:"TechWeekID: TW-5889
CalendarBlockID: TW-5889-SCHEDULE
RerankID: 5889
PartifulID: 4HvzWY1VZlHgK21fMBUz
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Tie security and data controls to audit-ready engineering evidence.
Ask: How are you proving AI-assisted engineering work was reviewed without leaking sensitive context?
Listen for: Security reviews, data access, compliance needs, audit trails, manager sign-off.
Follow-up: Offer a follow-up focused on source-linked evidence without surveillance dashboards.
RSVP status: applied
Category: primary
Venue basis: 23rd Street and 8th Avenue, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=23rd+Street+and+8th+Avenue%2C+New+York%2C+NY
Rank/tier/score: 16 / S / 80
URL: https://partiful.com/e/4HvzWY1VZlHgK21fMBUz?c=g5NbnbjN"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: Building secure AI for your data: DeepFellow Demo + Q&A -> The Future of Coding Agents and IDE", start date:date "2026-06-03 13:35", end date:date "2026-06-03 14:00", location:"Building secure AI for your data: DeepFellow Demo + Q&A -> 1155 6th Ave, New York, NY 10036", description:"TechWeekID: TW-4444
CalendarBlockID: TW-4444-TRAVEL-IN
RerankID:
PartifulID: 1N6CtiCpYquktoTh5NUm
Walk 4 min to 23 St (A/C/E); subway 11 min; walk 5 min from Times Sq-42 St (GS); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: Building secure AI for your data: DeepFellow Demo + Q&A -> 1155 6th Ave, New York, NY 10036 ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.744081%2C-73.999562&destination=40.7564611%2C-73.9831996&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/1N6CtiCpYquktoTh5NUm"}
	make new event at end of events of scheduleCal with properties {summary:"[REG] The Future of Coding Agents and IDE", start date:date "2026-06-03 14:00", end date:date "2026-06-03 15:00", location:"1155 6th Ave, New York, NY 10036", description:"TechWeekID: TW-4444
CalendarBlockID: TW-4444-SCHEDULE
RerankID: 4444
PartifulID: 1N6CtiCpYquktoTh5NUm
On the list; monitor for updates Submitted via Partiful API; Partiful live sync 2026-05-12: rsvpStatus=APPROVED; count=2; plusOne=TBD; approved 2026-05-11 00:23 ET.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Talk about the IDE as the point where human and agent work blur.
Ask: When agents write code, what human work still needs credit?
Listen for: Prompting, spec writing, review corrections, architectural judgment, tool orchestration.
Follow-up: Ask to sanity-check the Accolades framing with builders using coding agents daily.
RSVP status: registered
Category: primary
Venue basis: 1155 6th Ave, New York, NY 10036 (manual_exact_manhattan)
Google Maps: https://www.google.com/maps/search/?api=1&query=1155+6th+Ave%2C+New+York%2C+NY+10036
Rank/tier/score: 27 / A / 72
URL: https://partiful.com/e/1N6CtiCpYquktoTh5NUm"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Quick food / reset", start date:date "2026-06-03 15:00", end date:date "2026-06-03 15:30", location:"Midtown", description:"TechWeekID:
CalendarBlockID: TW-20260603-MEAL-FOOD
RerankID:
PartifulID:
Hectic-day 30-minute grab-and-go slot before the next walk.
RSVP status: registered
Category: meal
Venue basis: Midtown (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=Midtown+Manhattan%2C+New+York%2C+NY
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: The Future of Coding Agents and IDE -> Fireside chat - When coding agents are the user?", start date:date "2026-06-03 15:40", end date:date "2026-06-03 16:00", location:"The Future of Coding Agents and IDE -> New York, NY", description:"TechWeekID: TW-5529
CalendarBlockID: TW-5529-TRAVEL-IN
RerankID:
PartifulID: E8NhJNHWGhMetLlrFvQ7
Walk approx 20 min / 1595 m using OSM-geocoded points.
RSVP status: registered
Category: travel
Venue basis: The Future of Coding Agents and IDE -> New York, NY ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7564611%2C-73.9831996&destination=40.7458%2C-73.9888&travelmode=walking
Rank/tier/score:  /  /
URL: https://partiful.com/e/E8NhJNHWGhMetLlrFvQ7"}
	make new event at end of events of scheduleCal with properties {summary:"[REG] Fireside chat - When coding agents are the user?", start date:date "2026-06-03 16:00", end date:date "2026-06-03 17:15", location:"New York, NY", description:"TechWeekID: TW-5529
CalendarBlockID: TW-5529-SCHEDULE
RerankID: 5529
PartifulID: E8NhJNHWGhMetLlrFvQ7
Registered; monitor for updates Submitted via Partiful API; rsvpStatus=GOING; count=2; plusOne=TBD.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use the event title directly: if agents are users, the system of record matters.
Ask: If the agent is the user, what becomes the system of record for useful work?
Listen for: Tool schemas, docs, prompts, guardrails, review evidence, ownership boundaries.
Follow-up: Ask for feedback on whether Accolades should track agent-orchestration evidence explicitly.
RSVP status: registered
Category: primary
Venue basis: 28th Street and Broadway, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=28th+Street+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: 15 / S / 81
URL: https://partiful.com/e/E8NhJNHWGhMetLlrFvQ7"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: Fireside chat - When coding agents are the user? -> MCP in the Wild: Panel & Night of Networking", start date:date "2026-06-03 17:40", end date:date "2026-06-03 18:00", location:"Fireside chat - When coding agents are the user? -> East Village", description:"TechWeekID: TW-4664
CalendarBlockID: TW-4664-TRAVEL-IN
RerankID:
PartifulID: 6ZuudQBBZXcMNjdMynJ2
Walk 1 min to 28 St (N/Q/R/W); subway 13 min; walk 1 min from Astor Pl (4/6); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: Fireside chat - When coding agents are the user? -> East Village ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7458%2C-73.9888&destination=40.72985%2C-73.99139&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/events/6ZuudQBBZXcMNjdMynJ2"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] MCP in the Wild: Panel & Night of Networking", start date:date "2026-06-03 18:00", end date:date "2026-06-03 20:30", location:"East Village", description:"TechWeekID: TW-4664
CalendarBlockID: TW-4664-SCHEDULE
RerankID: 4664
PartifulID: 6ZuudQBBZXcMNjdMynJ2
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: MCP people will understand context plumbing. Map that to later evaluation.
Ask: What context should tools expose so contribution can be evaluated after the work ships?
Listen for: Tool-call trails, context sources, agent actions, human review, integration ownership.
Follow-up: Ask for technical feedback on evidence capture from tool and agent workflows.
RSVP status: applied
Category: primary
Venue basis: Astor Place, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Astor+Place%2C+New+York%2C+NY
Rank/tier/score: 58 / A / 63
URL: https://partiful.com/events/6ZuudQBBZXcMNjdMynJ2"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Dinner after MCP in the Wild", start date:date "2026-06-03 20:30", end date:date "2026-06-03 21:30", location:"East Village", description:"TechWeekID:
CalendarBlockID: TW-20260603-MEAL-DINNER
RerankID:
PartifulID:
One-hour meal buffer before heading home.
RSVP status: registered
Category: meal
Venue basis: East Village (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=East+Village%2C+New+York%2C+NY
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: MCP in the Wild: Panel & Night of Networking -> 15 Cliff Street, New York, NY 10038", start date:date "2026-06-03 21:30", end date:date "2026-06-03 21:51", location:"MCP in the Wild: Panel & Night of Networking -> 15 Cliff Street, New York, NY 10038", description:"TechWeekID: TW-4664
CalendarBlockID: TW-20260603-TRAVEL-HOME
RerankID:
PartifulID: 6ZuudQBBZXcMNjdMynJ2
Walk 1 min to Astor Pl (4/6); subway 12 min; walk 3 min from Fulton St (2/3); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: MCP in the Wild: Panel & Night of Networking -> 15 Cliff Street, New York, NY 10038 ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.72985%2C-73.99139&destination=40.7084297%2C-74.0056635&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/events/6ZuudQBBZXcMNjdMynJ2"}
	make new event at end of events of scheduleCal with properties {summary:"Sleep: 8 hours", start date:date "2026-06-04 03:15", end date:date "2026-06-04 11:15", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260604-SLEEP
RerankID:
PartifulID:
Staggered late sleep block; night-to-night bedtime shift stays within 30 minutes.
RSVP status: registered
Category: sleep
Venue basis: 15 Cliff Street, New York, NY 10038 (sleep_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: 15 Cliff Street, New York, NY 10038 -> The Semiconductor & AI Supply Chain Lunch: Investors & Operators", start date:date "2026-06-04 11:59", end date:date "2026-06-04 12:30", location:"15 Cliff Street, New York, NY 10038 -> Nomad", description:"TechWeekID: TW-6642
CalendarBlockID: TW-6642-TRAVEL-IN
RerankID:
PartifulID: WJe6XcxPXwbpCiCVLCas
Walk 3 min to Fulton St (2/3); subway 22 min; walk 1 min from 28 St (N/Q/R/W); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: 15 Cliff Street, New York, NY 10038 -> Nomad ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7084297%2C-74.0056635&destination=40.7458%2C-73.9888&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/WJe6XcxPXwbpCiCVLCas"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] The Semiconductor & AI Supply Chain Lunch: Investors & Operators", start date:date "2026-06-04 12:30", end date:date "2026-06-04 14:00", location:"Nomad", description:"TechWeekID: TW-6642
CalendarBlockID: TW-6642-SCHEDULE
RerankID: 6642
PartifulID: WJe6XcxPXwbpCiCVLCas
Latest-feed add with no direct conflict; keep on the route if approved, otherwise use as a reference-only lunch option. Wait for host approval Existing Partiful guest record found; left unchanged. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added-route
Venue basis: 28th Street and Broadway, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=28th+Street+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: added-12 / B / 51
URL: https://partiful.com/e/WJe6XcxPXwbpCiCVLCas"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Late lunch / reset", start date:date "2026-06-04 14:30", end date:date "2026-06-04 15:30", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260604-MEAL-LUNCH
RerankID:
PartifulID:
One-hour meal buffer before leaving for the Thursday route.
RSVP status: registered
Category: meal
Venue basis: 15 Cliff Street, New York, NY 10038 (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: The Semiconductor & AI Supply Chain Lunch: Investors & Operators -> Shipping Faster with AI Coding Agents: What's Working and What's Not", start date:date "2026-06-04 15:46", end date:date "2026-06-04 16:00", location:"The Semiconductor & AI Supply Chain Lunch: Investors & Operators -> New York, NY", description:"TechWeekID: TW-5372
CalendarBlockID: TW-5372-TRAVEL-IN
RerankID:
PartifulID: 5K5c4eODrGPKME7or20H
Walk 1 min to 28 St (N/Q/R/W); subway 8 min; walk 0 min from Prince St (N/Q/R/W); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: The Semiconductor & AI Supply Chain Lunch: Investors & Operators -> New York, NY ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7458%2C-73.9888&destination=40.724329%2C-73.997702&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/5K5c4eODrGPKME7or20H"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] Shipping Faster with AI Coding Agents: What's Working and What's Not", start date:date "2026-06-04 16:00", end date:date "2026-06-04 18:38", location:"New York, NY", description:"TechWeekID: TW-5372
CalendarBlockID: TW-5372-SCHEDULE
RerankID: 5372
PartifulID: 5K5c4eODrGPKME7or20H
Leave early if needed so you can make the registered 19:00 Stop Making AI Guess event. Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none. Route calendar shortens this from the event's scheduled 19:00 end; leave 22 min early for transit.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: This is a direct AI-coding workflow room. Start with manager trust.
Ask: What changed in your review process after AI started writing more code?
Listen for: Review overload, shallow approvals, unclear ownership, productivity claims without evidence.
Follow-up: Ask for a buyer call with the engineering leader responsible for AI coding adoption.
RSVP status: applied
Category: primary
Venue basis: Spring St and Broadway, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Spring+St+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: 4 / S / 100
URL: https://partiful.com/e/5K5c4eODrGPKME7or20H"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: Shipping Faster with AI Coding Agents: What's Working and What's Not -> Stop Making AI Guess: When Your Codebase Becomes the Spec", start date:date "2026-06-04 18:38", end date:date "2026-06-04 19:00", location:"Shipping Faster with AI Coding Agents: What's Working and What's Not -> Union Square", description:"TechWeekID: TW-5114
CalendarBlockID: TW-5114-TRAVEL-IN
RerankID:
PartifulID: X0u5GrmzvIUTrjoAOgVm
Leave previous event 22 min before its scheduled end.
Walk approx 22 min / 1755 m using OSM-geocoded points.
RSVP status: registered
Category: travel
Venue basis: Shipping Faster with AI Coding Agents: What's Working and What's Not -> Union Square ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.724329%2C-73.997702&destination=40.735736%2C-73.990568&travelmode=walking
Rank/tier/score:  /  /
URL: https://partiful.com/e/X0u5GrmzvIUTrjoAOgVm"}
	make new event at end of events of scheduleCal with properties {summary:"[REG] Stop Making AI Guess: When Your Codebase Becomes the Spec", start date:date "2026-06-04 19:00", end date:date "2026-06-04 20:45", location:"Union Square", description:"TechWeekID: TW-5114
CalendarBlockID: TW-5114-SCHEDULE
RerankID: 5114
PartifulID: X0u5GrmzvIUTrjoAOgVm
Registered direct. This is the Thursday anchor unless a substantially better curated dinner approves. Registered; monitor for updates Submitted via Partiful API; rsvpStatus=GOING; count=2; plusOne=TBD.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use the codebase-as-spec theme and make Accolades feel complementary.
Ask: What would make a codebase trustworthy enough for agents and managers?
Listen for: Source-linked context, specs in code, review trails, stale docs, manager confidence.
Follow-up: Ask to exchange notes on codebase evidence and Accolades after the event.
RSVP status: registered
Category: apply
Venue basis: Union Square, Manhattan, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Union+Square%2C+Manhattan%2C+New+York%2C+NY
Rank/tier/score: 21 / S / 76
URL: https://partiful.com/e/X0u5GrmzvIUTrjoAOgVm"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Dinner after Stop Making AI Guess", start date:date "2026-06-04 20:45", end date:date "2026-06-04 21:45", location:"Union Square", description:"TechWeekID:
CalendarBlockID: TW-20260604-MEAL-DINNER
RerankID:
PartifulID:
One-hour meal buffer before heading home.
RSVP status: registered
Category: meal
Venue basis: Union Square (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=Union+Square%2C+Manhattan%2C+New+York%2C+NY
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: Stop Making AI Guess: When Your Codebase Becomes the Spec -> 15 Cliff Street, New York, NY 10038", start date:date "2026-06-04 21:45", end date:date "2026-06-04 22:04", location:"Stop Making AI Guess: When Your Codebase Becomes the Spec -> 15 Cliff Street, New York, NY 10038", description:"TechWeekID: TW-5114
CalendarBlockID: TW-20260604-TRAVEL-HOME
RerankID:
PartifulID: X0u5GrmzvIUTrjoAOgVm
Walk 0 min to 14 St-Union Sq (N/Q/R/W); subway 11 min; walk 3 min from Fulton St (2/3); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: Stop Making AI Guess: When Your Codebase Becomes the Spec -> 15 Cliff Street, New York, NY 10038 ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.735736%2C-73.990568&destination=40.7084297%2C-74.0056635&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/X0u5GrmzvIUTrjoAOgVm"}
	make new event at end of events of scheduleCal with properties {summary:"Sleep: 8 hours", start date:date "2026-06-05 03:45", end date:date "2026-06-05 11:45", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260605-SLEEP
RerankID:
PartifulID:
Staggered late sleep block; night-to-night bedtime shift stays within 30 minutes.
RSVP status: registered
Category: sleep
Venue basis: 15 Cliff Street, New York, NY 10038 (sleep_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Meal: Early dinner before Bare Metal", start date:date "2026-06-05 15:10", end date:date "2026-06-05 16:10", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260605-MEAL-DINNER
RerankID:
PartifulID:
One-hour food buffer before the Friday evening event.
RSVP status: registered
Category: meal
Venue basis: 15 Cliff Street, New York, NY 10038 (meal_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: 15 Cliff Street, New York, NY 10038 -> Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration", start date:date "2026-06-05 16:21", end date:date "2026-06-05 17:00", location:"15 Cliff Street, New York, NY 10038 -> Union Square", description:"TechWeekID: TW-5722
CalendarBlockID: TW-5722-TRAVEL-IN
RerankID:
PartifulID: jkjGahQgmH9PLIxjfTFt
Walk 3 min to Fulton St (2/3); subway 27 min; walk 4 min from 14 St-Union Sq (N/Q/R/W); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: 15 Cliff Street, New York, NY 10038 -> Union Square ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7084297%2C-74.0056635&destination=40.7365763%2C-73.9885429&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/jkjGahQgmH9PLIxjfTFt"}
	make new event at end of events of scheduleCal with properties {summary:"[PENDING] Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration", start date:date "2026-06-05 17:00", end date:date "2026-06-05 20:00", location:"Union Square", description:"TechWeekID: TW-5722
CalendarBlockID: TW-5722-SCHEDULE
RerankID: 5722
PartifulID: jkjGahQgmH9PLIxjfTFt
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: For agent fleet and autonomous systems people, focus on orchestration accountability.
Ask: How do teams know who did useful orchestration, review, and correction work across agent fleets?
Listen for: Multi-agent coordination, operations work, incident reviews, hidden platform labor.
Follow-up: Ask for intros to platform leads running agent or automation infrastructure.
RSVP status: applied
Category: primary
Venue basis: Union Square Park, 201 Park Ave S, New York, NY 10003 (exact_from_partiful_maps)
Google Maps: https://www.google.com/maps/search/?api=1&query=Union+Square+Park%2C+201+Park+Ave+S%2C+New+York%2C+NY+10003
Rank/tier/score: 45 / A / 64
URL: https://partiful.com/e/jkjGahQgmH9PLIxjfTFt"}
	make new event at end of events of scheduleCal with properties {summary:"Travel: Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration -> 15 Cliff Street, New York, NY 10038", start date:date "2026-06-05 20:00", end date:date "2026-06-05 20:23", location:"Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration -> 15 Cliff Street, New York, NY 10038", description:"TechWeekID: TW-5722
CalendarBlockID: TW-20260605-TRAVEL-HOME
RerankID:
PartifulID: jkjGahQgmH9PLIxjfTFt
Walk 4 min to 14 St-Union Sq (N/Q/R/W); subway 11 min; walk 3 min from Fulton St (2/3); includes 5 min buffer.
RSVP status: registered
Category: travel
Venue basis: Bare Metal Happy Hour: Autonomous Systems & Agent Fleet Orchestration -> 15 Cliff Street, New York, NY 10038 ()
Google Maps: https://www.google.com/maps/dir/?api=1&origin=40.7365763%2C-73.9885429&destination=40.7084297%2C-74.0056635&travelmode=transit
Rank/tier/score:  /  /
URL: https://partiful.com/e/jkjGahQgmH9PLIxjfTFt"}
	make new event at end of events of scheduleCal with properties {summary:"Sleep: 8 hours", start date:date "2026-06-06 04:15", end date:date "2026-06-06 12:15", location:"15 Cliff Street, New York, NY 10038", description:"TechWeekID:
CalendarBlockID: TW-20260606-SLEEP
RerankID:
PartifulID:
Staggered late sleep block after the final Tech Week route day.
RSVP status: registered
Category: sleep
Venue basis: 15 Cliff Street, New York, NY 10038 (sleep_buffer)
Google Maps: https://www.google.com/maps/search/?api=1&query=15+Cliff+Street%2C+New+York%2C+NY+10038
Rank/tier/score:  /  /
URL:"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] The builder’s table: AI finance leaders lunch with Vayu, Base44 & PwC", start date:date "2026-06-01 14:30", end date:date "2026-06-01 16:00", location:"Midtown", description:"TechWeekID: TW-6493
CalendarBlockID: TW-6493-REFERENCE
RerankID: 6493
PartifulID: MQvS9RrcXl6HcAEzfzhg
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: Bryant Park, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Bryant+Park%2C+New+York%2C+NY
Rank/tier/score: added-10 / B / 52
URL: https://partiful.com/e/MQvS9RrcXl6HcAEzfzhg"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING BACKUP] Slack x Amplitude: AI at work", start date:date "2026-06-01 17:00", end date:date "2026-06-01 18:30", location:"Tribeca", description:"TechWeekID: TW-5110
CalendarBlockID: TW-5110-REFERENCE
RerankID: 5110
PartifulID: dmFBKIxzn2LdFmktqas8
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use the Slack angle: work decisions often happen outside GitHub.
Ask: Which important engineering decisions live in Slack, and do they ever make it into reviews or planning?
Listen for: Slack decisions, cross-functional handoffs, lost context, collaboration evidence.
Follow-up: Ask whether Slack-linked contribution credit would help managers or team leads.
RSVP status: applied
Category: backup
Venue basis: Fabrik, 16 Vestry St, New York, NY 10013 (exact_from_partiful_maps)
Google Maps: https://www.google.com/maps/search/?api=1&query=Fabrik%2C+16+Vestry+St%2C+New+York%2C+NY+10013
Rank/tier/score: 180 / B / 53
URL: https://partiful.com/e/dmFBKIxzn2LdFmktqas8"}
	make new event at end of events of referenceCal with properties {summary:"[REG BACKUP] Software for Hardware: The Tools Powering Robotics & Embodied AI", start date:date "2026-06-01 18:00", end date:date "2026-06-01 21:00", location:"Civic Hall, 124 E 14th St 2nd Floor, New York, NY", description:"TechWeekID: TW-5962
CalendarBlockID: TW-5962-REFERENCE
RerankID: 5962
PartifulID: 09a0qPKv0cSOIOSGxjTQ
Partiful registered only. Secondary Luma checkout is $20 and was explicitly skipped. Partiful registered; skip paid Luma checkout Submitted via Partiful API; rsvpStatus=GOING; count=1; plusOne=none. Secondary Luma link requires $20 paid ticket; user explicitly said do not complete checkout.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Hardware and robotics teams have heavy coordination work before code ships.
Ask: How do you credit specs, integration debugging, reviews, and ops work across hardware/software boundaries?
Listen for: Systems integration, test evidence, field debugging, cross-discipline ownership.
Follow-up: Ask for founder/operator feedback rather than pushing a pure software-team sale.
RSVP status: registered
Category: backup
Venue basis: Civic Hall, 124 E 14th St, New York, NY 10003 (exact_from_event_page)
Google Maps: https://www.google.com/maps/search/?api=1&query=Civic+Hall%2C+124+E+14th+St%2C+New+York%2C+NY+10003
Rank/tier/score: 13 / S / 86
URL: https://partiful.com/e/09a0qPKv0cSOIOSGxjTQ"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] Fintech Engineers Happy Hour", start date:date "2026-06-01 18:00", end date:date "2026-06-01 19:30", location:"SoHo", description:"TechWeekID: TW-6506
CalendarBlockID: TW-6506-REFERENCE
RerankID: 6506
PartifulID: pmDosvwgBQPxLVDk8WWb
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: Spring St and Broadway, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Spring+St+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: added-13 / B / 50
URL: https://partiful.com/e/pmDosvwgBQPxLVDk8WWb"}
	make new event at end of events of referenceCal with properties {summary:"[REG BACKUP] NYC B2B: AI Founders & Investors Mixer", start date:date "2026-06-01 18:30", end date:date "2026-06-01 20:00", location:"Skinos, 123 Washington St, New York, NY", description:"TechWeekID: TW-4200
CalendarBlockID: TW-4200-REFERENCE
RerankID: 4200
PartifulID: oQvmxTsHOVayx47ok3li
Registered backup near FiDi. Use if Open Source Must Win is not approved or is too low signal in practice. Registered; monitor for updates Submitted via Partiful API; rsvpStatus=GOING; count=2; plusOne=TBD.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: This is broad B2B. Keep the pitch short and qualify fast.
Ask: Does your engineering team use GitHub and Slack heavily enough that contribution visibility is a management problem?
Listen for: Founder with 5+ engineers, remote team, AI coding adoption, performance-review pain.
Follow-up: Ask for a warm intro to the CTO or VP Eng if the person is not the buyer.
RSVP status: registered
Category: backup
Venue basis: Skinos, 123 Washington St, New York, NY (exact_from_signup_status)
Google Maps: https://www.google.com/maps/search/?api=1&query=Skinos%2C+123+Washington+St%2C+New+York%2C+NY
Rank/tier/score: 169 / B / 54
URL: https://partiful.com/e/oQvmxTsHOVayx47ok3li?c=0hT1WkMm"}
	make new event at end of events of referenceCal with properties {summary:"[WAITLIST BACKUP] Operating MCP", start date:date "2026-06-02 16:00", end date:date "2026-06-02 19:00", location:"TBC", description:"TechWeekID: TW-4522
CalendarBlockID: TW-4522-REFERENCE
RerankID: 4522
PartifulID: 5vHvRPI0VlMQwOmQadCN
Monitor waitlist / host approval Submitted via Partiful API; rsvpStatus=WAITLIST; count=2; plusOne=TBD.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: For MCP/control-plane conversations, talk about instrumenting context and actions.
Ask: What needs to be logged so a manager can understand who influenced an agent-driven outcome?
Listen for: Context sources, tool permissions, traceability, review responsibility, platform ownership.
Follow-up: Ask to compare notes with anyone building internal agent infrastructure.
RSVP status: waitlisted
Category: backup
Venue basis: Bryant Park, New York, NY (approx_freeform_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Bryant+Park%2C+New+York%2C+NY
Rank/tier/score: 7 / S / 98
URL: https://partiful.com/e/5vHvRPI0VlMQwOmQadCN"}
	make new event at end of events of referenceCal with properties {summary:"[REG BACKUP] AI, Algorithms & Liability: What Tech Leaders & Creators Need to Know", start date:date "2026-06-02 17:30", end date:date "2026-06-02 19:30", location:"One Battery Park Plaza, 7th Floor New York, NY 10004", description:"TechWeekID: TW-5415
CalendarBlockID: TW-5415-REFERENCE
RerankID: 5415
PartifulID: UBrZopzqpRwbn6Qk0npO
On the list; monitor for updates Submitted via Partiful API; Partiful live sync 2026-05-12: rsvpStatus=APPROVED; count=1; plusOne=none; approved 2026-05-11 18:49 ET.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use liability language carefully: evidence, review, and accountability.
Ask: If AI-assisted work causes a problem, what evidence would you want before assigning responsibility?
Listen for: Audit trails, legal/compliance sensitivity, review records, decision provenance.
Follow-up: Ask if source-linked engineering evidence would be useful for compliance conversations.
RSVP status: registered
Category: backup
Venue basis: Wall St, New York, NY (approx_freeform_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Wall+St%2C+New+York%2C+NY
Rank/tier/score: 72 / B / 58
URL: https://partiful.com/e/UBrZopzqpRwbn6Qk0npO?c=4IfpVNvT"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING BACKUP] WorkOS + Postman Agents & APIs Demo Night", start date:date "2026-06-02 17:30", end date:date "2026-06-02 19:30", location:"56 Greene Street, 4th Floor New York, NY 10012", description:"TechWeekID: TW-4224
CalendarBlockID: TW-4224-REFERENCE
RerankID: 4224
PartifulID: XqIBMZmB4oubCZWFP2Sl
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: API and identity demos are a good opening for permissions plus evidence.
Ask: When agents call internal APIs, how do you audit who requested, reviewed, and approved the work?
Listen for: API governance, permissions, review evidence, enterprise buyers, workflow logs.
Follow-up: Ask for intros to teams responsible for developer platform or internal API governance.
RSVP status: applied
Category: backup
Venue basis: Spring St and Broadway, New York, NY (approx_freeform_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Spring+St+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: 217 / B / 51
URL: https://partiful.com/e/XqIBMZmB4oubCZWFP2Sl"}
	make new event at end of events of referenceCal with properties {summary:"[REG ADDED] AI on Main Street: How Chinatown's Small Businesses Are Using AI", start date:date "2026-06-02 17:30", end date:date "2026-06-02 19:00", location:"Chinatown", description:"TechWeekID: TW-6393
CalendarBlockID: TW-6393-REFERENCE
RerankID: 6393
PartifulID: hl2AIeWhZ1e2t6LveEGw
Registered; monitor for updates Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=GOING; count=2; plusOne=TBD.
RSVP status: registered
Category: latest-added
Venue basis: Chinatown, Manhattan, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Chinatown%2C+Manhattan%2C+NY
Rank/tier/score: added-11 / B / 51
URL: https://partiful.com/e/hl2AIeWhZ1e2t6LveEGw"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING CURATED] Enterprise AI Happy Hour", start date:date "2026-06-02 18:00", end date:date "2026-06-02 19:30", location:"SoHo", description:"TechWeekID: TW-5437
CalendarBlockID: TW-5437-REFERENCE
RerankID: 5437
PartifulID: FSzOO6xPn11iqxVdtQ9j
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Enterprise AI buyers care about governance and platform ownership.
Ask: Where do manager reports and audit evidence fit into your enterprise AI rollout?
Listen for: Governance, internal platforms, production agents, executive reporting, risk controls.
Follow-up: Ask for a specific post-event call with the platform, DevEx, or AI governance owner.
RSVP status: applied
Category: apply
Venue basis: Spring St and Broadway, New York, NY (approx_freeform_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Spring+St+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: 2 / S / 100
URL: https://partiful.com/e/FSzOO6xPn11iqxVdtQ9j?"}
	make new event at end of events of referenceCal with properties {summary:"[REG BACKUP] Cloudflare + Shopify: Build for the Agent Era", start date:date "2026-06-02 18:00", end date:date "2026-06-02 20:00", location:"Shopify New York, 131 Greene St, New York, NY 10012", description:"TechWeekID: TW-5925
CalendarBlockID: TW-5925-REFERENCE
RerankID: 5925
PartifulID: jytNb4IdG0HxwJnqDSgf
On the list; monitor for updates Submitted via Partiful API; Partiful live sync 2026-05-12: rsvpStatus=APPROVED; count=1; plusOne=none; approved 2026-05-12 12:57 ET.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use infrastructure scale as the bridge into contribution evidence.
Ask: In the agent era, what evidence do infra teams need to trust work done across tools and systems?
Listen for: Platform scale, agent infrastructure, toolchain visibility, engineering productivity.
Follow-up: Ask for technical feedback from infra leaders rather than a generic founder follow-up.
RSVP status: registered
Category: backup
Venue basis: Shopify New York, 131 Greene St, New York, NY 10012 (exact_from_signup_status)
Google Maps: https://www.google.com/maps/search/?api=1&query=Shopify+New+York%2C+131+Greene+St%2C+New+York%2C+NY+10012
Rank/tier/score: 23 / S / 75
URL: https://partiful.com/e/jytNb4IdG0HxwJnqDSgf"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] Founders x Investors AI Toolkit & Happy Hour", start date:date "2026-06-02 18:00", end date:date "2026-06-02 19:30", location:"Midtown", description:"TechWeekID: TW-6629
CalendarBlockID: TW-6629-REFERENCE
RerankID: 6629
PartifulID: Vs2eC7nERtgF0PgNWfUo
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: Bryant Park, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Bryant+Park%2C+New+York%2C+NY
Rank/tier/score: added-7 / B / 54
URL: https://partiful.com/e/Vs2eC7nERtgF0PgNWfUo"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING CURATED] Anthropic Founder Salon: Inside the AI-Native Era", start date:date "2026-06-03 13:30", end date:date "2026-06-03 17:00", location:"New York, NY - Chelsea neighborhood (venue details upon confirmation)", description:"TechWeekID: TW-5820
CalendarBlockID: TW-5820-REFERENCE
RerankID: 5820
PartifulID: titPml1Nw0DKwGl9B6CF
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: AI-native founders will understand the operating-model shift.
Ask: How do AI-native teams evaluate human contribution when agents produce more of the visible output?
Listen for: Small teams scaling fast, agent-heavy workflows, contribution rewards, manager memory breaking down.
Follow-up: Ask for a founder-to-founder product critique and one relevant buyer intro.
RSVP status: applied
Category: apply
Venue basis: 23rd Street and 8th Avenue, New York, NY (approx_freeform_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=23rd+Street+and+8th+Avenue%2C+New+York%2C+NY
Rank/tier/score: 9 / S / 94
URL: https://partiful.com/e/titPml1Nw0DKwGl9B6CF"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING CURATED] Agent Harnesses: What It Takes to Make AI Agents Work in the Enterprise", start date:date "2026-06-03 16:00", end date:date "2026-06-03 21:00", location:"Union Square", description:"TechWeekID: TW-4719
CalendarBlockID: TW-4719-REFERENCE
RerankID: 4719
PartifulID: 2NP0rZW8BmdGAGUOEhGP
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Agent harnesses are about production reliability; connect that to human accountability.
Ask: What human evidence needs to sit beside the harness output before an enterprise trusts agent work?
Listen for: Enterprise adoption, internal platforms, review gates, evaluation records, ownership.
Follow-up: Ask to discuss how Accolades could consume evidence from agent harness workflows.
RSVP status: applied
Category: apply
Venue basis: Union Square W, New York, NY 10003 (exact_from_partiful_maps)
Google Maps: https://www.google.com/maps/search/?api=1&query=Union+Square+W%2C+New+York%2C+NY+10003
Rank/tier/score: 8 / S / 97
URL: https://partiful.com/e/2NP0rZW8BmdGAGUOEhGP?f=1"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] Voice AI Meetup: Build a Voice Agent in 1 hour", start date:date "2026-06-03 17:00", end date:date "2026-06-03 18:30", location:"SoHo", description:"TechWeekID: TW-4882
CalendarBlockID: TW-4882-REFERENCE
RerankID: 4882
PartifulID: pIS8aostHgPm9GXmaN6X
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: Spring St and Broadway, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Spring+St+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: added-14 / B / 50
URL: https://partiful.com/e/pIS8aostHgPm9GXmaN6X"}
	make new event at end of events of referenceCal with properties {summary:"[REG CURATED] The CTO Mixer: Humanizing Tech | Happy Hour", start date:date "2026-06-03 17:30", end date:date "2026-06-03 19:30", location:"Midtown, Manhattan, New York, NY", description:"TechWeekID: TW-4778
CalendarBlockID: TW-4778-REFERENCE
RerankID: 4778
PartifulID: h1hGv0PkskcagJOv5M9K
On the list; monitor for updates Partiful page shows ON THE LIST as of 2026-05-10. Previously submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: This is a direct CTO room. Ask about pain before explaining the product.
Ask: What is hardest for your managers to evaluate now that AI touches more engineering work?
Listen for: Performance reviews, planning evidence, PR quality, distributed-team context, DevEx ownership.
Follow-up: If pain is clear, ask for a 20-minute CTO follow-up and permission to send a one-pager.
RSVP status: registered
Category: apply
Venue basis: Astor Place, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Astor+Place%2C+New+York%2C+NY
Rank/tier/score: 6 / S / 100
URL: https://partiful.com/e/h1hGv0PkskcagJOv5M9K"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING BACKUP] Camp AI: Agents at Work", start date:date "2026-06-03 17:30", end date:date "2026-06-03 20:30", location:"620 8th Ave, New York, NY 10018", description:"TechWeekID: TW-5693
CalendarBlockID: TW-5693-REFERENCE
RerankID: 5693
PartifulID: Fp5STyPH0McEt0awlWFD
Wait for host approval Submitted via Partiful API after user confirmed age 21+; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Keep this practical: agents at work means work attribution is getting messy.
Ask: When an agent helps ship something, who gets credit for the useful parts of the workflow?
Listen for: Agent orchestration, prompt/spec work, review corrections, workflow ownership.
Follow-up: Ask for examples of workflows Accolades should recognize or avoid recognizing.
RSVP status: applied
Category: backup
Venue basis: 620 8th Ave, New York, NY 10018 (manual_exact_manhattan)
Google Maps: https://www.google.com/maps/search/?api=1&query=620+8th+Ave%2C+New+York%2C+NY+10018
Rank/tier/score: 19 / S / 78
URL: https://partiful.com/e/Fp5STyPH0McEt0awlWFD"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] Tessera Labs x a16z : The Closing Gap (Private Dinner)", start date:date "2026-06-03 17:30", end date:date "2026-06-03 19:00", location:"Flatiron", description:"TechWeekID: TW-4931
CalendarBlockID: TW-4931-REFERENCE
RerankID: 4931
PartifulID: tPlMvExfd6gOdgKCW6O7
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: 23rd Street and Broadway, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=23rd+Street+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: added-5 / B / 55
URL: https://partiful.com/e/tPlMvExfd6gOdgKCW6O7"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] Data Center, Power & Enterprise Infrastructure Dinner", start date:date "2026-06-03 18:00", end date:date "2026-06-03 19:30", location:"Central Park", description:"TechWeekID: TW-5720
CalendarBlockID: TW-5720-REFERENCE
RerankID: 5720
PartifulID: Vkvjr5dBr2FmbI2yK5UB
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: Central Park, Manhattan, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Central+Park%2C+Manhattan%2C+NY
Rank/tier/score: added-1 / A / 73
URL: https://partiful.com/e/Vkvjr5dBr2FmbI2yK5UB"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] SGLang Happy Hour: AI Infra in Finance", start date:date "2026-06-03 18:00", end date:date "2026-06-03 19:30", location:"SoHo", description:"TechWeekID: TW-6519
CalendarBlockID: TW-6519-REFERENCE
RerankID: 6519
PartifulID: p74X9KDrgoLaDtU8BmvS
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: Spring St and Broadway, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Spring+St+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: added-2 / A / 67
URL: https://partiful.com/e/p74X9KDrgoLaDtU8BmvS"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING CURATED] The Tech Leaders Suite", start date:date "2026-06-03 19:00", end date:date "2026-06-03 21:00", location:"Brooklyn", description:"TechWeekID: TW-4197
CalendarBlockID: TW-4197-REFERENCE
RerankID: 4197
PartifulID: UhyErPPxuo2vELIutdGj
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use leadership language: visibility without surveillance.
Ask: What evidence do tech leaders wish they had for planning and reviews without turning into surveillance?
Listen for: Manager reporting, trust, team health, engineering productivity, executive visibility.
Follow-up: Ask for a leadership-focused follow-up if they manage engineers or internal platforms.
RSVP status: applied
Category: apply
Venue basis: Barclays Center, Brooklyn, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Barclays+Center%2C+Brooklyn%2C+NY
Rank/tier/score: 5 / S / 100
URL: https://partiful.com/e/UhyErPPxuo2vELIutdGj?"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] The Mooch and IBM’s Gary Cohn on Owning the Future: Digital Sovereignty in the Age of AI", start date:date "2026-06-04 13:00", end date:date "2026-06-04 14:30", location:"Flatiron", description:"TechWeekID: TW-6526
CalendarBlockID: TW-6526-REFERENCE
RerankID: 6526
PartifulID: tUV88fW7J763Q0ZLdTBI
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: 23rd Street and Broadway, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=23rd+Street+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: added-22 / B / 49
URL: https://partiful.com/e/tUV88fW7J763Q0ZLdTBI"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] Built in NYC: AI Edition", start date:date "2026-06-04 16:00", end date:date "2026-06-04 17:30", location:"Flatiron", description:"TechWeekID: TW-6577
CalendarBlockID: TW-6577-REFERENCE
RerankID: 6577
PartifulID: KIimVVdYB8fjaiE1UdZz
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: 23rd Street and Broadway, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=23rd+Street+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: added-24 / B / 49
URL: https://partiful.com/e/KIimVVdYB8fjaiE1UdZz"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING BACKUP] Agents at Scale", start date:date "2026-06-04 18:00", end date:date "2026-06-04 20:00", location:"SoHo", description:"TechWeekID: TW-4191
CalendarBlockID: TW-4191-REFERENCE
RerankID: 4191
PartifulID: 6BlGFmwIdpyndqyLYS2v
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: For agent scale, focus on attribution across many automated steps.
Ask: When agents run at scale, how do you separate valuable human judgment from automated output?
Listen for: Evaluation gaps, agent ops, review ownership, platform labor, traceability.
Follow-up: Ask to learn how they log agent work today and whether source-linked credit would fit.
RSVP status: applied
Category: backup
Venue basis: Spring St and Broadway, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Spring+St+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: 10 / S / 93
URL: https://partiful.com/e/6BlGFmwIdpyndqyLYS2v?c=bv5YqCoL"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING BACKUP] Steal These AI Workflows: Live Demos from NYC's Top AI Builders", start date:date "2026-06-04 18:00", end date:date "2026-06-04 19:30", location:"Union Square", description:"TechWeekID: TW-4826
CalendarBlockID: TW-4826-REFERENCE
RerankID: 4826
PartifulID: sGvp4VIr3KrGqRoWCKhV
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none. Secondary Google Form submitted for UbiquityOS Accolades build demo.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: This is a live-demo room. Use your own build story, then ask about workflow data.
Ask: Which parts of your AI workflow create useful evidence that managers should see later?
Listen for: Prompting, issue specs, PRs, Slack decisions, demos that could become repeatable workflows.
Follow-up: Ask demo builders to name one evidence source Accolades should integrate first.
RSVP status: applied
Category: backup
Venue basis: Union Square E, New York, NY 10003 (exact_from_partiful_maps)
Google Maps: https://www.google.com/maps/search/?api=1&query=Union+Square+E%2C+New+York%2C+NY+10003
Rank/tier/score: 34 / A / 66
URL: https://partiful.com/e/sGvp4VIr3KrGqRoWCKhV"}
	make new event at end of events of referenceCal with properties {summary:"[WAITLIST CURATED] Engineering Leaders After Hours: A Build and Ship Cocktail Competition", start date:date "2026-06-04 18:30", end date:date "2026-06-04 21:30", location:"Bar Chef, 21 W 35th St,, New York, NY 10001", description:"TechWeekID: TW-4183
CalendarBlockID: TW-4183-REFERENCE
RerankID: 4183
PartifulID: bETmU06uq4TtORng6I1l
Monitor waitlist / host approval Submitted via Partiful API; Partiful live sync 2026-05-12: rsvpStatus=WAITLISTED_FOR_APPROVAL; count=1; plusOne=none; moved to waitlist 2026-05-11 10:32 ET.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: This may be the best direct engineering-manager room. Be crisp and buyer-oriented.
Ask: What do your managers use as evidence when deciding who moved a project forward?
Listen for: Performance-review pain, review quality, planning work, manager memory, team rewards.
Follow-up: Ask for a concrete follow-up with the engineering leader or manager who owns the pain.
RSVP status: waitlisted
Category: apply
Venue basis: Bar Chef, 21 W 35th St,, New York, NY 10001 (exact_from_signup_status)
Google Maps: https://www.google.com/maps/search/?api=1&query=Bar+Chef%2C+21+W+35th+St%2C%2C+New+York%2C+NY+10001
Rank/tier/score: 20 / S / 78
URL: https://partiful.com/e/bETmU06uq4TtORng6I1l"}
	make new event at end of events of referenceCal with properties {summary:"[REG CURATED] AI BUILDERS DINNER", start date:date "2026-06-04 19:00", end date:date "2026-06-04 21:00", location:"Flatiron, Manhattan, New York, NY", description:"TechWeekID: TW-5231
CalendarBlockID: TW-5231-REFERENCE
RerankID: 5231
PartifulID: idltitmjA4ZzL9IuK0Y6
On the list; monitor for updates Submitted via Partiful API; Partiful live sync 2026-05-12: rsvpStatus=APPROVED; count=1; plusOne=none; approved 2026-05-10 11:04 ET.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: At dinner, sell softly. Use founder-to-founder learning first.
Ask: How are AI builders changing how they reward and evaluate work inside their teams?
Listen for: AI-native operating models, fast-growing teams, founder pain, engineering leadership gaps.
Follow-up: Ask for one sharp product critique and one relevant engineering-leader intro.
RSVP status: registered
Category: apply
Venue basis: 23rd Street and Broadway, New York, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=23rd+Street+and+Broadway%2C+New+York%2C+NY
Rank/tier/score: 11 / S / 90
URL: https://partiful.com/e/idltitmjA4ZzL9IuK0Y6"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING BACKUP] From Prediction Markets to Predictive Intelligence Systems", start date:date "2026-06-04 19:00", end date:date "2026-06-04 20:30", location:"Financial District", description:"TechWeekID: TW-5204
CalendarBlockID: TW-5204-REFERENCE
RerankID: 5204
PartifulID: eSldi3iNIvAVo9utdd8S
Wait for host approval Submitted via Partiful API; live update 2026-05-26: rsvpStatus=PENDING_APPROVAL; count=2; plusOne=Juinqe Lynn.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: This is less direct; use prediction and decision quality as the bridge.
Ask: How do you know which people or artifacts actually improved a technical decision?
Listen for: Decision provenance, forecasts versus outcomes, accountability, source-linked context.
Follow-up: Only pursue deep follow-up if they have an engineering team with GitHub/Slack pain.
RSVP status: applied
Category: backup
Venue basis: Wall St, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Wall+St%2C+New+York%2C+NY
Rank/tier/score: 89 / B / 57
URL: https://partiful.com/e/eSldi3iNIvAVo9utdd8S"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING ADDED] Founders, Investors & Builders — An Intimate NYC Cocktail Evening", start date:date "2026-06-04 19:00", end date:date "2026-06-04 20:30", location:"Union Square", description:"TechWeekID: TW-6594
CalendarBlockID: TW-6594-REFERENCE
RerankID: 6594
PartifulID: PhqnW15PCQAdoENB6aNl
Wait for host approval Submitted via Partiful API; linkedPlusOneFailures=0. rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
RSVP status: applied
Category: latest-added
Venue basis: Union Square, Manhattan, New York, NY (approx_from_calendar_location)
Google Maps: https://www.google.com/maps/search/?api=1&query=Union+Square%2C+Manhattan%2C+New+York%2C+NY
Rank/tier/score: added-6 / B / 55
URL: https://partiful.com/e/PhqnW15PCQAdoENB6aNl"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING BACKUP] Free Phos, Real Convos. Agents in your DMs", start date:date "2026-06-04 20:00", end date:date "2026-06-04 21:30", location:"Flatiron", description:"TechWeekID: TW-5207
CalendarBlockID: TW-5207-REFERENCE
RerankID: 5207
PartifulID: ed2EFWip0do9OuYmVPZI
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none. Required follow questions answered truthfully as Not yet.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Use the DM/agent framing to talk about decisions in conversational channels.
Ask: When agents and teammates work in DMs, what context should be preserved for later credit or audit?
Listen for: Slack/DM work, agent conversations, missing provenance, informal decisions.
Follow-up: Ask for feedback on Slack-first evidence capture if the person runs engineering workflows.
RSVP status: applied
Category: backup
Venue basis: Pho Dragon Restaurant, 47 W 14th St, New York, NY 10011 (exact_from_partiful_maps)
Google Maps: https://www.google.com/maps/search/?api=1&query=Pho+Dragon+Restaurant%2C+47+W+14th+St%2C+New+York%2C+NY+10011
Rank/tier/score: 18 / S / 79
URL: https://partiful.com/e/ed2EFWip0do9OuYmVPZI"}
	make new event at end of events of referenceCal with properties {summary:"[PENDING CURATED] YouCode AI Salon", start date:date "2026-06-05 18:00", end date:date "2026-06-05 21:00", location:"New York, NY", description:"TechWeekID: TW-250
CalendarBlockID: TW-250-REFERENCE
RerankID: 250
PartifulID: kvGpuFMeACW7ZWPYtxTP
Wait for host approval Submitted via Partiful API; rsvpStatus=PENDING_APPROVAL; count=1; plusOne=none.
Sales coaching:
Pitch: Accolades credits the engineering work commit counts miss, using source-linked GitHub and Slack evidence.
Open: Treat this as a lower-pressure builder salon and look for AI-native founders.
Ask: How does your team credit prompt work, specs, review, and product judgment around AI coding?
Listen for: Builder workflows, early team habits, contribution rewards, technical-founder pain.
Follow-up: Ask for feedback or an intro; do not over-invest unless they match the ICP.
RSVP status: applied
Category: apply
Venue basis: Barclays Center, Brooklyn, NY (approx_neighborhood_hidden)
Google Maps: https://www.google.com/maps/search/?api=1&query=Barclays+Center%2C+Brooklyn%2C+NY
Rank/tier/score: 26 / A / 73
URL: https://partiful.com/e/kvGpuFMeACW7ZWPYtxTP"}
end tell
